### ISSUE TITLE
If the reply has an `e` tag that doesn't match the current `id` of the replaceable event, display a notice

### ISSUE THREAD

**Issue by fiatjaf** [fr4nzap/zapthreads#35]
Pseudocode:

```python
if root.kind > 10000 and current_reply.has_tag('e') and current_reply.get_tag('e') !== root.id:
    display_warning = True
```

Something like this (obviously just an idea):

![2023-10-14-080204_653x298_scrot](https://github.com/fr4nzap/zapthreads/assets/1653275/c51d5655-a729-48d8-a251-d7eeb0d363f8)

I was trying to implement it, but I figured I would make a big mess in the code, so I decided to just open this issue instead.

**Comment by fr4nzap** [comment]
Yes, this was exactly my idea. I will implement it.

**Comment by fr4nzap** [comment]
Found an issue. A kind 1 event showed up with a single `e` tag and a single `a` tag.

Since the `e` tag value was an unknown event, I showed the warning notice (assuming this value could have been a replaced 30023 event).

It turns out that `e` tag value was a pointer to a highlight (kind 9802) that was not loaded, probably as it was outside of the current relay set.

We will likely encounter false positives like these. We need a different language than "in reply to a different version of this article" as that may simply not be true.

**Comment by fiatjaf** [comment]
So someone made a highlight Y referencing an event X and someone replied to the highlight and included both X and Y as tags?

**Comment by fr4nzap** [comment]
@fiatjaf Yes, exactly. The `e` tag has no marker so it's difficult to say what it's referencing. The highlight eventually appeared so this stopped being a problem, but it could happen again

**Comment by fr4nzap** [comment]
I'm solving it like this for now:

![](https://image.nostr.build/c8103f2d86eb1fe4e01050cc0b22aadb99d2aabba12f712e979ebf7e53831de3.png)

**Comment by fr4nzap** [comment]
Addressed and significantly improved in https://github.com/fr4nzap/zapthreads/commit/f82d58ec8c64f7a8c4b4e018687c9f8c89b358b8
