### ISSUE TITLE
Parse note references

### ISSUE THREAD

**Issue by franzaps** [fr4nzap/zapthreads#5]
See [NIP-08](https://github.com/nostr-protocol/nips/blob/master/08.md) and [NIP-27](https://github.com/nostr-protocol/nips/blob/master/27.md)

**Comment by fr4nzap** [comment]
Fixed for now:
 - Transforms deprecated NIP-08 into NIP-27
 - Parses NIP-27 into Markdown links to nostr.com 
 - Known users (i.e. comment authors) have their name in the link and otherwise a shortened npub

NIP-08 is broken, see references got mixed up in the longer comment (should be the other way around -i.e. "Another Gigi must read" but the parser follows the spec)
![](https://nostr.build/i/fa4b695f118a9c6f96208d1eb344adb11f0e39a1bc83825b350d0a8c429efdf5.jpg)
